# Generated by Django 2.2.6 on 2019-10-30 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_todoitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 30, 21, 53, 50, 731611)),
        ),
    ]
