# Generated by Django 2.2.6 on 2019-10-30 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20191030_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 30, 22, 0, 37, 302131)),
        ),
    ]
