# Generated by Django 2.2.6 on 2019-11-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='status',
            field=models.TextField(default='inProgress'),
        ),
    ]
