# Generated by Django 2.2.6 on 2019-10-30 22:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20191030_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 30, 22, 1, 52, 143950, tzinfo=utc)),
        ),
    ]
