# Generated by Django 2.2.6 on 2019-10-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20191030_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
