# Generated by Django 2.2.6 on 2019-11-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_todoitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.TextField(default='todo'),
        ),
    ]
