# Generated by Django 2.2.6 on 2019-11-19 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20191119_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='status',
        ),
    ]
