# Generated by Django 2.2.6 on 2019-11-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_todoitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='status',
            field=models.TextField(default='todo'),
        ),
    ]
