# Generated by Django 2.2.6 on 2019-11-24 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_todoitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('body', models.TextField(default='')),
                ('user', models.TextField(default='')),
                ('todoItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.TodoItem')),
            ],
        ),
    ]
