# Generated by Django 2.2.6 on 2019-11-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20191124_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.TextField(default='todo'),
        ),
    ]
