# Generated by Django 2.2.6 on 2019-11-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        #('course', '__latest__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNum', models.IntegerField()),
                ('title', models.CharField(default='nullCourse', max_length=100)),
                ('instructor', models.CharField(max_length=250)),
                ('maxEnrollment', models.IntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
    ]
