# Generated by Django 2.2.6 on 2019-11-18 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_todoitem_user'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='relatedItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.TodoItem'),
        ),
    ]
