# Generated by Django 2.2.7 on 2019-11-24 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_newsitem_relateditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='creator',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
