# Generated by Django 2.2.6 on 2019-11-25 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20191124_2301'),
        ('login', '0003_auto_20191124_1944'),
    ]

    operations = [
    ]
