# Generated by Django 2.2.6 on 2019-11-12 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='enrolledStud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.IntegerField()),
                ('firstName', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=250)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Course')),
                ('members', models.ManyToManyField(limit_choices_to={'courseID': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Course')}, to='course.enrolledStud')),
            ],
        ),
    ]
