# Generated by Django 2.2.6 on 2019-11-11 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '__latest__'),
        ('course', '0001_initial')
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledstud',
            name='courseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Course'),
        ),
        migrations.AlterField(
            model_name='project',
            name='courseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Course'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
