# Generated by Django 2.2.6 on 2019-10-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='nullCourse', max_length=100),
        ),
    ]
