# Generated by Django 2.2.6 on 2019-10-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_todoitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='date',
            field=models.DateField(default='1999-01-13'),
        ),
    ]
